# Generated by Django 5.2.9 on 2025-12-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professionals", "0002_professional_created_at_professional_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="professional",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
