# Generated by Django 5.2.9 on 2025-12-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_appointment_created_at_appointment_updated_at"),
        ("professionals", "0003_alter_professional_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appointment",
            options={"ordering": ["date"]},
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("professional", "date"), name="unique_appointment_professional_date"
            ),
        ),
    ]
